name: Health Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  health_check_ing:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-bfwp.onrender.com/health
